image: codehz/stonebuilder
stages:
  - build
  - package

variables:
  GIT_SUBMODULE_STRATEGY: recursive

job_build:
  script:
    - mkdir build
    - cd build
    - cmake .. || (cat CMakeFiles/CMakeOutput.log && cat CMakeFiles/CMakeError.log && exit 1)
    - make
  artifacts:
    paths:
      - build/stone/stone
    expire_in: 20min
  stage: build

job_package:
  script:
    - mkdir -p output/support && cd output
    - cat ../lib32.txt | xargs -I {} cp -Lrv /usr/lib32/{} support/{}
    - cp -Lv /usr/lib32/ld-*.so support/ld.so
    - cp ../build/stone/stone .
  artifacts:
    paths:
      - output
  only:
    - master@codehz/StoneServer
  dependencies:
    - job_build
  stage: package